version: "3"

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - "./client/public:/app/public:ro"
      - "./client/src:/app/src:ro"
  client_test:
    build: ./client
    command: npm run validate
    volumes:
      - "./client/coverage:/app/coverage"
      - "./client/public:/app/public:ro"
      - "./client/src:/app/src"
  db:
    env_file:
      - ./config/docker_dev.env
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  db_setup:
    build:
      args:
        - MIX_ENV=dev
      context: ./server
    command: ./scripts/wait-for-it.sh db:5432 --strict -t 30 -- mix ecto.setup
    depends_on:
      - db
    env_file:
      - ./config/docker_dev.env
  e2e:
    build: ./e2e
    command: ./scripts/wait-for-it.sh client:3000 --strict -t 30 -- npm test
    depends_on:
      - client
    environment:
      - CYPRESS_baseUrl=http://client:3000
    volumes:
      - "./e2e/cypress/screenshots:/app/cypress/screenshots"
      - "./e2e/cypress/videos:/app/cypress/videos"
  e2e_test:
    build: ./e2e
    command: npm run validate
  server:
    command: mix phx.server
    depends_on:
      - db
      - db_setup
    env_file:
      - ./config/docker_dev.env
    image: freedomaccount_db_setup
    ports:
      - "4000:4000"
    volumes:
      - "./server/config:/app/config:ro"
      - "./server/lib:/app/lib:ro"
      - "./server/priv:/app/priv:ro"
  server_test:
    build:
      args:
        - MIX_ENV=test
      context: ./server
    command: ./scripts/wait-for-it.sh db:5432 --strict -t 30 -- mix validate
    depends_on:
      - db
    env_file:
      - ./config/docker_test.env
    volumes:
      - "./server/config:/app/config"
      - "./server/cover:/app/cover"
      - "./server/lib:/app/lib"
      - "./server/_plts:/app/_plts"
      - "./server/priv:/app/priv:ro"
      - "./server/test:/app/test"

volumes:
  dbdata:
