version: "3"

services:
  db:
    image: postgres:11.2
    env_file:
      - ./config/db_variables.env
    volumes:
      - ./.db/data:/var/lib/postgresql/data

  server:
    build: "./server"
    depends_on:
      - db
    env_file:
      - ./config/db_variables.env
    environment:
      - MIX_ENV=dev
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - "./server:/app"

  server_test:
    command: mix test.all
    depends_on:
      - db
    env_file:
      - ./config/db_variables.env
    environment:
      - MIX_ENV=test
    image: freedomaccount_server
    volumes:
      - "./server:/app"
