version: "3"

services:
  db:
    image: postgres:11.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.db/data:/var/lib/postgresql/data

  server:
    build: "./server"
    depends_on:
      - db
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    ports:
      - "4000:4000"
    volumes:
      - "./server:/app"
