version: "3"

services:
  app:
    command: foreground
    depends_on:
      - db
      - db_setup
    env_file:
      - ./config/docker_prod.env
      - ./config/docker_prod_secret.env
    image: freedom_account_prod_db_setup
    ports:
      - "8080:4000"
  db:
    image: postgres:11.2-alpine
    env_file:
      - ./config/docker_prod.env
      - ./config/docker_prod_secret.env
    volumes:
      - dbdata:/var/lib/postgresql/data
  db_setup:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    command: seed
    depends_on:
      - db
    env_file:
      - ./config/docker_prod.env
      - ./config/docker_prod_secret.env

volumes:
  dbdata:
